# 如果不需要多环境配置，删除 spring.config.activate 块
spring:
  # config:
  #   activate:
  #     on-profile: dev
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///bank?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: Hck282018
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/public/

server:
  port: 80

mybatis:
  type-aliases-package: com.example.setweb.dao
  configuration:
    map-underscore-to-camel-case: true